### ISSUE TITLE
Manage Profiles swipe to delete

### ISSUE THREAD

**Issue by bmuramatsu** [openwallet-foundation-labs/learner-credential-wallet#327]
On individual profiles, should be able to swipe from right to delete like an individual credential. Should have same user flow as Delete Profile

**Comment by kayaelle** [comment]
Recommend we close this issue. Profiles has a way to delete and this is an area we will want to explore in the future beyond this functionality. @alexfigtree

**Comment by alexfigtree** [comment]
Closing
