### ISSUE TITLE
Create public link with Multiple VCs in a VP

### ISSUE THREAD

**Issue by kayaelle** [openwallet-foundation-labs/learner-credential-wallet#399]
From Pivotal list

Labels: none

status: unstarted

created Sep 21, 2022

by Brandon

Description:

**Comment by bmuramatsu** [comment]
Renamed, LCW should be able to send a VP containing multiple VCs to VerifierPlus and VerifierPlus would know how to create an appropriate public link. Requires work on VerifierPlus.

**Comment by alexfigtree** [comment]
Created this issue on web-verifier-plus: https://github.com/digitalcredentials/web-verifier-plus/issues/144

Closing this issue
