### ISSUE TITLE
Validate presentation separately from credentials therein

### ISSUE THREAD

**Issue by kayaelle** [openwallet-foundation-labs/learner-credential-wallet#401]
From Pivotal list

Labels: none

status: unscheduled

created Oct 5, 2021

by Kyle

Description: Currently the DCC Verifiable Credentials library performs both validation of presentation structure, and verification of the presentation's proof/challenge and the credentials' proofs inside all through one method `vc.verify`. We need to somehow validate the structure of a presentation, verify its signature if it is signed (deep link or otherwise with a challenge), and defer the credential verification to the next step (the UI for accepting/declining credentials). A user should be able to accept an unverified credential into their wallet (feature request from Brandon).

**Comment by alexfigtree** [comment]
Dmitri: says we should validate bundle (Verifiable Presentation) AS WELL AS each individual credential.

**Comment by alexfigtree** [comment]
Dmitri: When we're implementing this, needs discussion on how to communicate the VP's validation status to user.

**Comment by kayaelle** [comment]
There hasn't been a need for this. If there is one, we can plan.
