### ISSUE TITLE
Conduct Digital Promise Equity Review of LCW

### ISSUE THREAD

**Issue by bmuramatsu** [openwallet-foundation-labs/learner-credential-wallet#421]
Conduct a LER review based on Digital Promise criteria, see: [LER Inclusive Design: Product Certification](https://productcertifications.microcredentials.digitalpromise.org/explore/ler-inclusive-design-product-certification)

**Comment by kayaelle** [comment]
The LCW is a general purpose education wallet and the equity review is very specific to skills/competencies related LERs. Recommend that those who use this software to develop their own wallet, explore this review with Digital Promise.
