### ISSUE TITLE
Add nested (linked) display of multiple credentials related to one another.

### ISSUE THREAD

**Issue by bmuramatsu** [openwallet-foundation-labs/learner-credential-wallet#436]
CU would like to display their Big 10 Competency Credenential in LCW along with the individual competencies that make up the credential as individual, but nested / linked credentials.

Big 10 Credential
> Big 10 Competency #1
> Big 10 Competency #2
> ...
> Big 10 Competencey #10

This would require the ability to add a VC (may or may not be CLRv2) with the linked credentials, and would require implementation of a display template for the credentials.

Downstream this probably affects Send Credential, and Create Public Link (if the individual Publicly Linked credentials are link to an overall credential).

**Comment by bmuramatsu** [comment]
If we take this work on it would part of funded. I recommend should evaluating it and communicating with CU by end of July 2023. If we agree to proceed this should be implemented and tested by end of December 2023 to run deployments beginning January 2024 to meet grant deadlines.

**Comment by alexfigtree** [comment]
Gillian: talks with CU (College Unbound) imply that this (nested competencies) is not super urgent
Dmitri: this needs to be addressed in specific cases before applying generally

**Comment by kayaelle** [comment]
Closing. If/when wallet implements CLR or a new request is made for this, can revisit.
