### ISSUE TITLE
Q&A- Tec: Credential info bleeds into second PDF page.

### ISSUE THREAD

**Issue by alexfigtree** [openwallet-foundation-labs/learner-credential-wallet#621]
**Describe the bug**
Credential, when too long, will bleed into second PDF page.
![Screenshot 2024-06-18 at 2 26 36 PM](https://github.com/digitalcredentials/learner-credential-wallet/assets/3487193/0c71fe99-e7e3-44e1-b11c-0deef74fe52e)

**To Reproduce**
1. Create PDF to share with credential. Credential, when too long, will bleed into second PDF page.

**Expected behavior**
Credential should adjust in size in order to fit within first/only PDF page

**Comment by alexfigtree** [comment]
New template sent via email with fix on 7/25/24.

**Comment by alexfigtree** [comment]
9/25/24: Still waiting on Tec to see if we can close this ticket

**Comment by alexfigtree** [comment]
Checking in with Tec to see if this issue has been resolved.

**Comment by kayaelle** [comment]
We can re-open if need be.
